# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=centos
NAME=scos
STREAM=c9s
DESCRIPTION=CentOS Stream CoreOS 9
VERSION=9.0
MUTATE_OS_RELEASE=9
BUILDER_IMG=quay.io/centos-bootc/centos-bootc:stream9@sha256:70236424fb0ffb6a59e8e3d3cbc0df9f87bd3284ccbc70a93efd24da1e6544fb
MANIFEST=manifest-c9s.yaml
IMAGE_CONFIG=image-c9s.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
