# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=centos
NAME=scos
STREAM=c10s
DESCRIPTION=CentOS Stream CoreOS 10
VERSION=10.0
MUTATE_OS_RELEASE=10
BUILDER_IMG=quay.io/centos-bootc/centos-bootc:stream10@sha256:00a452f7d1dabe1cd10212e7787ceabc2d331e483b5612c38286a6d5cb0d2647
MANIFEST=manifest-c10s.yaml
IMAGE_CONFIG=image-c10s.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
