apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/joelcapitao/bootc-base-image-konflux?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (
        (event == "push" && target_branch == "main")
      ) && (
        ".tekton/fedora-bootc-rawhide-minimal-push.yaml".pathChanged() ||
        "Containerfile".pathChanged() ||
        "bootc-base-imagectl".pathChanged() ||
        "install-manifests".pathChanged() ||
        "fedora-includes/generic.yaml".pathChanged() ||
        "minimal.yaml".pathChanged() ||
        "minimal/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-bootc-rawhide
    appstudio.openshift.io/component: fedora-bootc-rawhide-minimal
    pipelines.appstudio.openshift.io/type: build
  name: fedora-bootc-rawhide-minimal-on-push
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args
    value:
    - REPOS_IMAGE=quay.io/bootc-devel/fedora-bootc-rawhide-compose:Fedora-Rawhide-20260126.n.0@sha256:821c4506243f80e735a4e756adbd2c0422e7e290271e1eaefd8996f96c60d791
    - MANIFEST=fedora-minimal
  - name: output-image
    value: quay.io/konflux-jcapitao-rh/bootc-tenant/fedora-bootc-rawhide-minimal:{{revision}}
  - name: labels
    value:
      - org.opencontainers.image.version=44
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:d29a4d1bc4f331a327e23d96ba48e4cdd2d8e732078faf6970dd9657e9b817e6
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
