apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/joelcapitao/bootc-base-image-konflux?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (
        (event == "push" && target_branch.startsWith("renovate/"))
      ) && (
        ".tekton/fedora-bootc-43-standard-renovate-push.yaml".pathChanged() ||
        "Containerfile".pathChanged() ||
        "bootc-base-imagectl".pathChanged() ||
        "install-manifests".pathChanged() ||
        "fedora-includes/generic.yaml".pathChanged() ||
        "minimal.yaml".pathChanged() ||
        "minimal/***".pathChanged() ||
        "minimal-plus.hidden.yaml".pathChanged() ||
        "minimal-plus/***".pathChanged() ||
        "standard.yaml".pathChanged() ||
        "standard/***".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: bootc-base-images
    appstudio.openshift.io/component: fedora-bootc-43-standard
    pipelines.appstudio.openshift.io/type: build
    release.appstudio.openshift.io/auto-release: "false"
  name: fedora-bootc-43-standard-renovate-on-push
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args
    value:
    - REPOS_IMAGE=quay.io/bootc-devel/fedora-bootc-43-compose:Fedora-43-updates-20260129.0@sha256:6cca2e955cc95413ee4f0e4c1385de21e753ae009357230ca478e12abcec3bdf
    - MANIFEST=fedora-standard
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/konflux-fedora/jcapitao-redhat-com-tenant/fedora-bootc-43-standard:{{revision}}
  - name: labels
    value:
      - org.opencontainers.image.version=43
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:d29a4d1bc4f331a327e23d96ba48e4cdd2d8e732078faf6970dd9657e9b817e6
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
  taskRunTemplate:
    serviceAccountName: build-pipeline-fedora-bootc-43-standard
